name: Pull Request Test

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
        clean: false

    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Hub\Editor\2020.3.1f1\Editor\Unity.exe" -batchmode -projectPath . -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile -
    
    - name : Unity Edit Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Hub\Editor\2020.3.1f1\Editor\Unity.exe" -batchmode -projectPath . -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile -
